spring:
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:file:~/test
      username: sa
      password:
      driverClassName: org.h2.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create
    show-sql: false

  main:
    banner-mode: "off"
  logging:
    pattern:
      console:
